#!/usr/bin/env python
import subprocess
interface = "etho"
new_mac = "00:11:22:33:44:88"
print("[+] Changing MAC address for "+interface+" to "+new_mac)
subprocess.call("ifconfig eth0 down", shell=True)
subprocess.call("ifconfig eth0 hw ether 00:11:22:33:44:88", shell=True)
subprocess.call("ifconfig eth0 up", shell=True)
